version: "3"

services:
#  db:
#    image: mariadb:latest
#    restart: always
#    volumes:
#      - ./.db_data:/var/lib/mysql/
#      - ./.dumps:/docker-entrypoint-initdb.d
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_USER=enso
#      - MYSQL_PASSWORD=1458d010ac35
#      - MYSQL_DATABASE=enso
#      - MYSQL_ROOT_PASSWORD=1458d010ac35
#
  php:
    build: ./php
    container_name: php
    working_dir: /var/www/html
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.env:/var/www/html/.env:ro
      - ./.composer-cache:/root/.composer/cache:delegated
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./enso-psr:/var/www/html
      - ./wait-for-it.sh:/wait-for-it.sh:ro
    expose:
      - "9000"
    command: >
        bash -c "composer install -o
        && docker-php-entrypoint php-fpm"
#    depends_on:
#      - db

  nginx:
    image: nginx:1.15
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./enso-psr:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf:ro
      - ./nginx/nginx-logs:/var/log/nginx:delegated
