#!/usr/bin/env php
<?php declare(strict_types = 1);

use Swoole\Http\
    {Request, Response, Server};
use Enso\Relay\
    {Response as EnsoResponse};

/** @var callable $run */
$run = require_once './entrypoint.php';

// create Swoole HTTP server
$httpServer = new Server(
    host: '0.0.0.0',
    port: 9999
);

$httpServer->set([
    'log_level' => 2
]);

// set request handler
$httpServer->on(
    event: 'request',
    callback: static function (Request $_request, Response $_response) use (&$run)
    {
        $connected_ts = $_request->server['request_time'];

        /** @var EnsoResponse $response */
        $response = $run ($_request);

        $_response = EnsoResponse::toSwooleResponse($response, $_response) // transform Enso -> Swoole response
            ->end(); // emit by Swoole

        gc_collect_cycles();
    }
);

// Swoole main coroutine
$httpServer->start();
