#!/usr/bin/env php
<?php declare(strict_types = 1);

use Enso\Relay\Response;
use HttpSoft\Message\ServerRequestFactory;
use HttpSoft\Message\StreamFactory;
use HttpSoft\Message\UploadedFileFactory;
use Spiral\RoadRunner;

/** @var callable $run */
$run = require_once './entrypoint.php';

// RR init
$serverRequestFactory = new ServerRequestFactory();
$streamFactory = new StreamFactory();
$uploadFactory = new UploadedFileFactory();

// RR worker
$_worker = RoadRunner\Worker::create();
$worker = new RoadRunner\Http\PSR7Worker($_worker, $serverRequestFactory, $streamFactory, $uploadFactory);

// RR loop
while ($request = $worker->waitRequest())
{
    try
    {
        /** @var Response $response */
        $response = $run($request); // inject RR request to entrypoint

        // emit response by RR
        $worker->respond($response);
    }
    catch (\Throwable $e)
    {
        $worker->getWorker()->error((string) $e);
    }
}
