#!/usr/bin/env php
<?php declare(strict_types = 1);

use Enso\Relay\Response;
use HttpSoft\Message\ServerRequestFactory;
use HttpSoft\Message\StreamFactory;
use HttpSoft\Message\UploadedFileFactory;
use Spiral\RoadRunner;

$run = require_once './entrypoint.php';

$serverRequestFactory = new ServerRequestFactory();
$streamFactory = new StreamFactory();
$uploadFactory = new UploadedFileFactory();

$_worker = RoadRunner\Worker::create();
$worker = new RoadRunner\Http\PSR7Worker($_worker, $serverRequestFactory, $streamFactory, $uploadFactory);

while ($request = $worker->waitRequest())
{
    try
    {
        /** @var Response $response */
        $response = $run($request);

        // RR emitting
        $worker->respond($response);
    }
    catch (\Throwable $e)
    {
        $worker->getWorker()->error((string) $e);
    }
}
